version: '3.5'  

services: 
  db:
    image: postgres:10.5
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: unless-stopped
  frontend: 
    image: frontend
    build: ./../4/example-frontend
    ports:
      - 5000:5000
  backend:
    image: backend
    build: ./../4/example-backend
    environment: 
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
    ports:
      - 8080:8080
    depends_on: 
    - db
  redis:
    image: redis
  reverse-proxy:
    image: nginx:latest
    volumes: 
      - ./../8/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
    - frontend
    - backend