version: '3.5'  

services: 
    frontend: 
      image: frontend
      build: ./example-frontend
      environment:
        - REACT_APP_BACKEND_URL=http://127.0.0.1:8080
      ports:
        - 5000:5000
    backend:
      image: backend
      build: ./example-backend
      ports:
        - 8080:8080
      environment:
        -  REQUEST_ORIGIN=http://localhost:5000
