version: '3.7'

services:
  blogfront:
    build: ./osa_5_fs2020
    ports:
      - 3000:3000
    depends_on:
        - backend
  backend:
    build: ./osa4_fs2020
    ports: 
      - 3001:3001
    volumes:
      - ./:/osa4_fs2020/usr/src/app # Let us modify the contents of the container locally
      - node_modules:/osa4_fs2020/usr/src/app /node_modules # A bit of node magic, this ensures the dependencies built for the image are not available locally.
    container_name: backend

volumes: # This is required for the node_modules named volume
  node_modules: